# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# Java / Hytale
java_version=26
hytale_version=0.7.0-pre.5
patchline=pre-release
manifest_server_version=>=0.7.0-pre.5 <0.8.0
# Project
group=dev.hynergy
version=0.0.1-dev
# Plugin metadata
mod_name=Hynergy
mod_description=# Hynergy
mod_url=https://hynergy.dev
mod_author=Seyager,RikuTatsu,Matrix848,Blovien
manifest_dependencies=Hytale:AssetModule=*
includes_pack=true