[package]
name = "hynergy-protocol"
version.workspace = true
edition.workspace = true

[dependencies]
hynergy-engine = { path = "../hynergy-engine" }
hynergy-model = { path = "../hynergy-model" }

[dev-dependencies]
hynergy-ffi = { path = "../hynergy-ffi" }
criterion = "0.8.2"

[[bench]]
name = "world_commands"
harness = false

[[bench]]
name = "definitions"
harness = false